"""Migración inicial para tabla users

Revision ID: fe0effba55c8
Revises: 
Create Date: 2024-11-13 06:27:44.402862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0effba55c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos_aprobacion')
    op.drop_table('aprobadores')
    op.drop_table('doc_receive')
    op.drop_table('invoices')
    op.drop_table('comprador')
    op.drop_table('vendedor')
    op.drop_table('invoices_lines')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_idws_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_idws_key', 'users', ['id_user_tax'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table('invoices_lines',
    sa.Column('id_line', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cufe', sa.VARCHAR(length=96), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('valor_total', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cufe'], ['invoices.cufe'], name='invoices_lines_cufe_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_line', name='invoices_lines_pkey')
    )
    op.create_table('vendedor',
    sa.Column('nitvendedor', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('razon_social', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('nombre_comercial', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('regimen_fiscal', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('actividad_economica', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('pais', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('departamento', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('municipio', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('mail', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('municipio_cod', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('departamento_cod', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('cod_tax1', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('ind_tax1', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('nitvendedor', name='vendedor_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('comprador',
    sa.Column('nitcomprador', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('razon_social', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('nombre_comercial', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('regimen_fiscal', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('pais', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('departamento', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('municipio', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('mail', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('municipio_cod', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('departamento_cod', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('cod_tax1', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('ind_tax1', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('nitcomprador', name='comprador_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('invoices',
    sa.Column('cufe', sa.VARCHAR(length=96), autoincrement=False, nullable=False),
    sa.Column('fecha_emision', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('tipo_doc', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('nitvendedor', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nitcomprador', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('no_fact', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('vendedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comprador_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hora_emision', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('moneda_doc', sa.VARCHAR(length=10), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('version_ubl', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('legal_iddoc', sa.VARCHAR(length=100), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('validacion_cod', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('fecha_validacion', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('hora_validacion', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('tipo_doc_cod', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('nota', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_envio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('hora_envio', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('ciudad_envio', sa.VARCHAR(length=100), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('departamento_envio', sa.VARCHAR(length=100), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('departamento_cod', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('direccion_envio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pais_emision', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('pago_id', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('pago_code', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('fecha_pago', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pago_tipo', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('valor_pago', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.Column('valor_impuestos_total', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.Column('ind_tax_factura', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('valor_base_impuestos', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.Column('valor_impuestos', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.Column('tarifa_impuestos', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.Column('id_tax_factura', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('nombre_tax_factura', sa.VARCHAR(length=100), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('valor_total_factura', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.Column('valor_impuestos_exc', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.Column('valor_impuestos_inc', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.Column('valor_descuentos', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.Column('valor_cargos', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.Column('nro_items_doc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aprobador', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aprobador'], ['users.id_user_tax'], name='invoices_aprobador_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['comprador_id'], ['users.id_user'], name='invoices_comprador_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nitcomprador'], ['comprador.nitcomprador'], name='invoices_nitcomprador_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nitvendedor'], ['vendedor.nitvendedor'], name='invoices_nitvendedor_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id_user'], name='invoices_vendedor_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cufe', name='invoices_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('doc_receive',
    sa.Column('id_doc', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_aprov', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('documento', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_recepcion', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_aprov'], ['aprobadores.id_aprobador'], name='doc_receive_id_aprov_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_doc', name='doc_receive_pkey')
    )
    op.create_table('aprobadores',
    sa.Column('id_aprobador', sa.INTEGER(), server_default=sa.text("nextval('aprobadores_id_aprobador_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idws_aprobador', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], name='aprobadores_id_user_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_aprobador', name='aprobadores_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('documentos_aprobacion',
    sa.Column('id_doc_aprobacion', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cufe', sa.VARCHAR(length=96), autoincrement=False, nullable=False),
    sa.Column('id_aprobador', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado_aprobacion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fecha_aprobacion', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('comentarios', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cufe'], ['invoices.cufe'], name='documentos_aprobacion_cufe_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_aprobador'], ['aprobadores.id_aprobador'], name='documentos_aprobacion_id_aprobador_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_doc_aprobacion', name='documentos_aprobacion_pkey')
    )
    # ### end Alembic commands ###
