services:
  - type: web
    name: appweone-backend
    env: python
    plan: free  # Cambia a "starter" o un plan pago si es necesario
    buildCommand: ""  # Render hará el build automáticamente si no se especifica nada aquí
    startCommand: "uvicorn backend.app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://db_1w_user:u1IqKAmko1dkYLKhUBsel4MdILV8WIuK@dpg-csgd9v88fa8c73fv14r0-a.oregon-postgres.render.com/db_1w"
      - key: SECRET_KEY
        value: "Myweone+"  # Cambia esto por tu propia clave secreta
    dockerfilePath: ./backend/Dockerfile  # Ubicación del Dockerfile
    autoDeploy: true
    healthCheckPath: "/docs"  # Verifica si Swagger está accesible para asegurar que la API está funcionando
